# NLP Text Classification

## classify sms as spam or ham by message length and punctuation

In [8]:
#imports
import numpy as np
import pandas as pd

#data
df = pd.read_csv('../UPDATED_NLP_COURSE/TextFiles/smsspamcollection.tsv', sep='\t')
print(df.columns , '\n')

#split
X = df[['length','punct']]
y = df['label']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#logistic model
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(solver='lbfgs')
lr_model.fit(X_train, y_train)
predictions = lr_model.predict(X_test)

#logistic evaluation
from sklearn import metrics
print('logistic regression evaluation:\n')
print(metrics.classification_report(y_test,predictions))
print(metrics.confusion_matrix(y_test,predictions), '\n')
print('accuracy score: ', metrics.accuracy_score(y_test,predictions), '\n\n')

#naive model
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
predictions = nb_model.predict(X_test)

#naive evaluation
print('naive bayes evaluation:\n')
print(metrics.classification_report(y_test,predictions))
print(metrics.confusion_matrix(y_test,predictions), '\n')
print('accuracy score:', metrics.accuracy_score(y_test,predictions), '\n\n')

#svm model
from sklearn.svm import SVC
svc_model = SVC(gamma='auto')
svc_model.fit(X_train,y_train)
predictions = svc_model.predict(X_test)

#svm evaluation
print('svm evaluation:\n')
print(metrics.classification_report(y_test,predictions))
print(metrics.confusion_matrix(y_test,predictions), '\n')
print('accuracy score:', metrics.accuracy_score(y_test,predictions), '\n\n')

Index(['label', 'message', 'length', 'punct'], dtype='object') 

logistic regression evaluation:

             precision    recall  f1-score   support

        ham       0.87      0.97      0.92      1593
       spam       0.10      0.02      0.03       246

avg / total       0.76      0.84      0.80      1839

[[1547   46]
 [ 241    5]] 

accuracy score:  0.843936922240348 


naive bayes evaluation:

             precision    recall  f1-score   support

        ham       0.87      0.99      0.93      1593
       spam       0.00      0.00      0.00       246

avg / total       0.75      0.86      0.80      1839

[[1583   10]
 [ 246    0]] 

accuracy score: 0.8607939097335509 


svm evaluation:

             precision    recall  f1-score   support

        ham       0.92      0.95      0.94      1593
       spam       0.60      0.47      0.52       246

avg / total       0.88      0.89      0.88      1839

[[1515   78]
 [ 131  115]] 

accuracy score: 0.8863512778684067 


